local_costmap:
  global_frame: sw1/odom
  robot_base_frame: sw1/base_footprint

  update_frequency: 10.0
  publish_frequency: 10.0
  transform_tolerance: 1.0  

  static_map: false  
  rolling_window: true
  width: 3
  height: 3
  resolution: 0.05
